name: Hosting Static Website
on:
push:
branches:
- '*'
jobs:
build:
name: Build Job
runs-on: ubuntu-latest
steps:
- name: 'Start build job'
run: |
echo "Starting the build job"
- name: 'Checkout'
uses: actions/checkout@v2
- name: 'Setup nodejs'
uses: actions/setup-node@v2
with:
node-version: '16'
- run: yarn install
- run: yarn build
- name: 'Write config'
run: |
mkdir ~/.oci
echo "[DEFAULT]" >> ~/.oci/config
echo "user=${{secrets.ocid1.user.oc1..aaaaaaaa5acohclykdcpv2frjqnzr5b6cbuw7b3fmnyola2frhnrebwxpn4a}}" >> ~/.oci/config
echo "fingerprint=${{secrets.04:dc:d7:2f:78:d4:28:df:68:f1:a8:75:20:08:c5:ee}}" >>
~/.oci/config
echo "=${{secrets.uk-london-1}}" >> ~/.oci/config
echo "=${{secrets.ocid1.tenancy.oc1..aaaaaaaaxmlt45veqj25r2m2qqldfuk4jjkr2m4lfo6a3vnyck4dbnxfx4ua}}" >>
~/.oci/config
echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
echo "${{secrets.MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCT6C3xJouDwkWX
CUn4YNYCA9PjUIwYuzbWgK2ArTxsvF+5NL1YUYNeQILQGMEiqlhJBMBuOAWpEs6T
ZW+Q+BIMTPenu3pzA4VkgCmCV6dK3ejf3dpfYMkXFPZD3jFmxFDVGj0iWh16SvrC
MvgzSqGOQzU0uvkEGT05478BRkyNbsN4cmQ3/0fPDtmKAAW/nwpsISToLaV6rh90
b6mHapAo/j84G6rCxUP0xpCfIRkiZo195Vx+QXdvsYKNtjfSV90fqxc9k8SoJyCP
WmMJwBGw/v7ydwBH3E9rlf5WF+XC79VbgSDzkbh6CkOZQwPXHR6LvVqqmfjw8QYO
8xi6yObVAgMBAAECggEAAd2b4WmAY65qUk1mXCEHPLSaUkkMe1i2iF4h0iMH8Bcw
M0CHDZDO/LwI6mG640UNeAj8pGdF1awhuZo981uDCW9ZxbPdB4uz0wtgJVTAYiFf
yUhzHguKfdALNdqc+j7fsNBz6ksDXteInN/SYaiUq8a36m0GrGvlFHswSEPVaLNI
EGOVSHcIjPZw7qeX2NUqC+KLJFSmgRaGalrybGSRraX3JtWIwP6gYpMFpXQQc5d7
6dl+1Lett2XPzXwpbXYnVK/amMnHm/k1Kf9rzk9nwPfEwBk0A5At6byrlkEKpa9W
WISL6gtHsCzWd1PmNPL4DR0tiNsmnxDk+nyEUfFmAQKBgQDFuSwVfkbjGVXAlSoe
9Cixf1FkQ1sbWKVuyCXNSJEIUPFkxcAcm0KmbHU4XNy7u3X45ZoDaweSGyTYH9cl
Nay2VtohchiT7VZo9QIfavfj7qcqPkLkQtxZUvzltDQZvWuZh+9Uhpjs0G1wCrN7
+c8WJXcQWrj/mosHQ1i5DNOTbQKBgQC/gDWvvioKSQdgDJ8JWMZigoNA/hLmf3G4
qJA5xB3YFhiUayA5jUa648DCpAIfkro6/qvBrh0Qjuo6wAzULH0S6UZySvOij57R
CTwKhDABDNBHiD5lsR7iglO7PIit3G/975O6scNoUlPAGWOzXpeh+Uzm/5A071KT
OCV6lRCYCQKBgQCJspjB6yxg8f7nXLp1ziIc4wcC5WmolMa5bQfufBANE5nZTWKq
SXJURoooE3vh/f59tSDaKoqeNOsm3J3Pmx7J6ZiF3FjDhHE+LQsqaCt1AHpIkA2z
u+CLEKFxM1tpZaJuzN1fJ1GO8uSUN8+hkmqnCLZvnE7kK3ORPlSmowkhzQKBgCTV
Bv5nR/S0eRurMcd9cKKv0YjllUMKDhhjK2JA6zCNh2q8c/U9y/XUKlYFb3cdJH6G
TwiwcVym8Dwehhkk+WVywp7m9Zc1omk4KnknVYhOK50mgkHS4ErWoD4p9WvjMxMX
SkWlPR1KgFs5RujP78Ayj+z6CIV15l70dJjwJMHpAoGAOLbLoclaW3sj6957V4te
hwvS7zBfjWgZD+yigk0yA6Mwyh3UWCOIPO9OY4AExiHs6fPMklMR58JPE2Pz9hC5
ei4Emt2yODzT8Q9OjSkbWHbz09kVNoksLRYx9nf9CYK2qkNTo0SQ7HE0Z/ckgJjo
XqqKqf3hdRXQ5aqXRnPSYQA=}}" >>
~/.oci/oci_api_key.pem
echo "${{secrets.ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCT6C3xJouDwkWXCUn4YNYCA9PjUIwYuzbWgK2ArTxsvF+5NL1YUYNeQILQGMEiqlhJBMBuOAWpEs6TZW+Q+BIMTPenu3pzA4VkgCmCV6dK3ejf3dpfYMkXFPZD3jFmxFDVGj0iWh16SvrCMvgzSqGOQzU0uvkEGT05478BRkyNbsN4cmQ3/0fPDtmKAAW/nwpsISToLaV6rh90b6mHapAo/j84G6rCxUP0xpCfIRkiZo195Vx+QXdvsYKNtjfSV90fqxc9k8SoJyCPWmMJwBGw/v7ydwBH3E9rlf5WF+XC79VbgSDzkbh6CkOZQwPXHR6LvVqqmfjw8QYO8xi6yObV}}" >>
~/.oci/oci_api_key_public.pem
- name: 'Install OCI CLI'
run: |
curl -L -O
https://raw.githubusercontent.com/oracle/ocicli/
master/scripts/install/install.sh
chmod +x install.sh
./install.sh --accept-all-defaults
echo "/home/runner/bin" >> $GITHUB_PATH
exec -l $SHELL
- name: 'Fix Config File Permissions'
run: |
oci setup repair-file-permissions --file
/home/runner/.oci/config
oci setup repair-file-permissions --file
/home/runner/.oci/oci_api_key.pem
- name: 'Deploy Into Object Storage'
run: |
oci os object bulk-delete -bn ${{secrets.os-react}}
--prefix static --force
oci os object put -bn ${{secrets.os-react}} --file
./build/manifest.json --content-type application/json --force
oci os object bulk-upload -bn ${{secrets.os-react}} -
-src-dir ./build --content-type text/html --include *.html --
overwrite
oci os object bulk-upload -bn ${{secrets.os-react}} -
-src-dir ./build --content-type image/jpeg --include *.jpg --
overwrite
oci os object bulk-upload -bn ${{secrets.os-react}} -
-src-dir ./build --content-type text/javascript --include *.js -
-overwrite
oci os object bulk-upload -bn ${{secrets.os-react}} -
-src-dir ./build --content-type text/css --include *.css --
overwrite
oci os object bulk-upload -bn ${{secrets.os-react

}} -
-src-dir ./build --content-type text/plain --exclude *.js --
exclude *.html --exclude *.jpg --exclude *.css --exclude
./build/manifest.json --overwrite
